name: Hello

on:
  workflow_dispatch:

jobs:
  
  hello:
    runs-on: ubuntu-22.04

    steps:

      - uses: actions/checkout@v7

      - name: hello
        run: echo "Hello world!!!" > hello.txt

      - name: get file
        uses: actions/upload-artifact@v7
        with:
          name: file
          path: hello.txt